# allocator_config.yml
# Notes:
# - All percentages are fractions (e.g., 0.70 = 70%).
# - Sector targets MUST sum to 1.0 inside the stocks sleeve.
# - Sleeve weights (stocks/etfs/commodities) should sum to 1.0 per portfolio.
# - Set planner.planner_only: true to skip the legacy auto-allocator (no code deleted).

portfolios:
  personal:
    portfolio_value: 125000     # ← edit anytime; planner sheets recompute

    planner:
      enabled: true
      planner_only: true
      # Shared ladder you requested (can override per-portfolio later if needed)
      share_ladder: [3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,102,153,204,255,306]
      show_sma_fraction: true   # true → show "x/3"; false → show 0..3

    sleeves:
      stocks_weight_pct: 0.70
      etfs_weight_pct: 0.20
      commodities_weight_pct: 0.10

    stocks:
      enabled: true
      per_ticker_cap_pct: 0.05      # max per single stock as % of TOTAL portfolio
      max_names_per_sector: 5
      sector_targets:
        Technology: 0.25
        Health Care: 0.15
        Financials: 0.12
        Industrials: 0.10
        Consumer Discretionary: 0.10
        Consumer Staples: 0.08
        Energy: 0.07
        Materials: 0.05
        Communication Services: 0.05
        Utilities: 0.02
        Real Estate: 0.01
      # Optional override of stock tickers for this portfolio only:
      # tickers: []

    etfs:
      enabled: true
      per_ticker_cap_pct: 0.10
      # Optional override ETF list just for this portfolio:
      # tickers: []

    commodities:
      enabled: true
      per_ticker_cap_pct: 0.10
      # Optional override commodity list just for this portfolio:
      # tickers: []

  retirement:
    portfolio_value: 310000

    planner:
      enabled: true
      planner_only: true
      share_ladder: [3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,102,153,204,255,306]
      show_sma_fraction: true

    sleeves:
      stocks_weight_pct: 0.60
      etfs_weight_pct: 0.30
      commodities_weight_pct: 0.10

    stocks:
      enabled: true
      per_ticker_cap_pct: 0.04
      max_names_per_sector: 6
      sector_targets:
        Technology: 0.22
        Health Care: 0.16
        Financials: 0.12
        Industrials: 0.12
        Consumer Discretionary: 0.10
        Consumer Staples: 0.10
        Energy: 0.06
        Materials: 0.05
        Communication Services: 0.04
        Utilities: 0.02
        Real Estate: 0.01
      # tickers: []

    etfs:
      enabled: true
      per_ticker_cap_pct: 0.12
      # tickers: []

    commodities:
      enabled: true
      per_ticker_cap_pct: 0.08
      # tickers: []

# (Optional) Legacy top-level keys can remain for backward compatibility,
# but are no longer necessary when everything is defined under `portfolios:`.
# The planner will prefer per-portfolio values and only fall back to top-level
# if a specific field is missing.
